# Generated by Django 5.1.4 on 2024-12-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='volume',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
