# Generated by Django 5.1.4 on 2024-12-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_alter_workout_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('distance', models.PositiveSmallIntegerField()),
                ('time', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
